console.log('Hello World!');
console.log('Hello' + 'World');
console.log('Hello ' + 'World');
console.log('Teaching the world how to code'.length);
console.log('codecademy'.toUpperCase());
console.log('    Remove whitespace    '.trim());
console.log(Math.random() * 100);
console.log(Math.floor(Math.random() * 100));
console.log(Math.ceil(43.8));
console.log(Number.isInteger(2017));